"""Add task analytics tables and fields

Revision ID: 07b794ad2b48
Revises: 
Create Date: 2025-06-14 12:54:29.569929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b794ad2b48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complexity_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('performance_metrics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('queue_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processing_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('first_response_time', sa.Float(), nullable=True))
        batch_op.create_index('idx_task_analytics_lookup', ['status', 'type', 'created_at'], unique=False)
        batch_op.create_index('idx_task_assigned_agent', ['assigned_agent_id'], unique=False)
        batch_op.create_index('idx_task_completed_at', ['completed_at'], unique=False)
        batch_op.create_index('idx_task_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_task_type_priority', ['type', 'priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_task_type_priority')
        batch_op.drop_index('idx_task_status_created')
        batch_op.drop_index('idx_task_completed_at')
        batch_op.drop_index('idx_task_assigned_agent')
        batch_op.drop_index('idx_task_analytics_lookup')
        batch_op.drop_column('first_response_time')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('quality_score')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('processing_time')
        batch_op.drop_column('queue_time')
        batch_op.drop_column('performance_metrics')
        batch_op.drop_column('complexity_score')

    # ### end Alembic commands ###
